version: '3.3'
services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker.env
    restart: always

  backend:
    build:
      context: ../bookmark/
    restart: always
    command: gunicorn bookmark.wsgi:application --bind 0:8000
    depends_on:
      - db
    env_file:
      - ./docker.env

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
